// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure for table sys_user.
type SysUser struct {
	Id            int64       `json:"id"            description:"user id"`
	NickName      string      `json:"nickName"      description:"用户昵称"`
	Email         string      `json:"email"         description:"邮箱地址"`
	AvatarPicture string      `json:"avatarPicture" description:"用户头像"`
	IsLocked      int         `json:"isLocked"      description:"是否锁定(1-是,0-否)"`
	IsDeleted     int         `json:"isDeleted"     description:"是否删除(1-是,0-否)"`
	LockedTime    *gtime.Time `json:"lockedTime"    description:"锁定时间"`
	DeletedTime   *gtime.Time `json:"deletedTime"   description:"删除时间"`
	CreateTime    *gtime.Time `json:"createTime"    description:"创建时间"`
	UpdateTime    *gtime.Time `json:"updateTime"    description:"更新时间"`
	Remark        string      `json:"remark"        description:"备注"`
}

func NewSysUser(id int64, nickName string, email string) *SysUser {
	return &SysUser{Id: id, NickName: nickName, Email: email}
}
