// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure of table sys_user for DAO operations like Where/Data.
type SysUser struct {
	g.Meta        `orm:"table:sys_user, do:true"`
	Id            interface{} // user id
	NickName      interface{} // 用户昵称
	Email         interface{} // 邮箱地址
	AvatarPicture interface{} // 用户头像
	IsLocked      interface{} // 是否锁定(1-是,0-否)
	IsDeleted     interface{} // 是否删除(1-是,0-否)
	LockedTime    *gtime.Time // 锁定时间
	DeletedTime   *gtime.Time // 删除时间
	CreateTime    *gtime.Time // 创建时间
	UpdateTime    *gtime.Time // 更新时间
	Remark        interface{} // 备注
}
