name: go-test
on:
  push:
    branches: [ main, develop ]
env:
  TEST_DEMO: hello-world

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: go test ./library/event/ -v
