# 规则描述：每天执行一次，将最近30天没有活跃且非BUG的ISSUE关闭
name: Issue Close Require

on:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: need close
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
#          token: ${{ secrets.GF_TOKEN }}
          labels: "inactive"
          inactive-day: 30
          exclude-labels: bug