name: Issue Close Require

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: need close
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
#          token: ${{ secrets.GF_TOKEN }}
          labels: 'inactive'
          inactive-day: 30
          exclude-labels: 'bug'